pluginManagement {
    repositories {
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
    }
}

rootProject.name = 'AbsServerTool'
include 'fabric', 'neoforge'
project(':fabric').projectDir = file('26.2Fabric')
project(':neoforge').projectDir = file('26.2NeoForge')
