plugins { id 'net.neoforged.moddev' }

neoForge {
    version = rootProject.neo_version
    runs {
        server { server(); programArgument '--nogui' }
    }
    mods { absservertool { sourceSet sourceSets.main } }
}

sourceSets.main.java.exclude 'abyssredemption/network/AbsServerNetworking.java'

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') { expand version: project.version }
}
